---
title: "RSY: MC2"
subtitle: "Studiengang Data Science (HS2022), FHNW"
author: "Jan Zwicky und Gabriel Torres"
date: "Letzte Aktualisierungen: `r format(Sys.time(), '%B %d, %Y')`"
output:
  bookdown::html_document2:
      code_folding: hide
      toc: true
      toc_depth: 3
      toc_float: true
      number_sections: true
editor_options: 
  chunk_output_type: console
---
<style>
#TOC {
  background-color: #F5F5F5;
  font-size: 16px;
}
#header{
  color: #708090;
  background-color: #F5F5F5;
  font-size: 30px;
}
body{
  color: #708090;
  background-color:#F5F5F5;
}
</style>

# Aufgabenstellung


# Daten aufbereiten und Pakete Lesen
## Pakete Laden und Daten Einlesen
In diesem Abschnitt werden alle Pakete geladen.
```{r, message = FALSE, warning = FALSE}

#Pakete f체r Data wrangling und Visualisierung
library(tidyverse)
library(ggplot2)
#Pakete f체r das HTML
library(bookdown)
library(knitr)
```

```{r setup, cache=TRUE}
knitr::opts_chunk$set(fit.align = 'left', cache = TRUE, warning = FALSE, message = FALSE)
```


```{r}
# Einlesen der CSV-Dateien
movies <- read.csv("ml-latest-small/movies.csv", sep = ",")
links <- read.csv("ml-latest-small/links.csv", sep = ",")
ratings <- read.csv("ml-latest-small/ratings.csv", sep = ",")
tags <- read.csv("ml-latest-small/tags.csv", sep = ",")
```

Welches sind die am h채ufigsten geschauten Filme?
```{r}
most_viewed <- movies%>%
  group_by(title,movieId,genres)%>%
  count()%>%
  ungroup()%>%
  filter(n == max(n))
```
Welches sind die am h채ufigsten geschauten Genres?

```{r}
genres_sep <-movies%>%
  separate_rows(genres,sep = "[^-a-zA-Z0-9\\s]+", convert = FALSE) %>%
  filter(genres!= "")
```

```{r}
ggplot(genres_sep,aes(genres))+
  geom_bar()
```
```{r}
genres_sep$value <- 1
```


```{r}
new_genres <- genres_sep %>%
  pivot_wider(names_from = genres, values_from = value) %>%
  select(-"no genres listed")
new_genres[is.na(new_genres)] <- 0
```

```{r}
genres_sep$genres
```

